# Cyber Writeup site settings
# Edit these three lines, then click "Commit changes".
title: My Cyber-Research
description: A beginner-friendly explainer on a Phishing.
author: Tristan Williams

# PICK YOUR LOOK: keep exactly ONE of these four lines without a # in front.
# To switch, put a # in front of the current one and remove the # from the new one.
#theme: jekyll-theme-hacker
theme: jekyll-theme-midnight
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate

# This must match your repository name, with a slash in front.
# Your repo should be named cyber-research. If you named it something else,
# change it here (for example "/my-other-name").
baseurl: "/Cyber-Research"

# Don't change anything below this line.
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
